config/routes.rb
TrendFinderFrontend::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => 'static_pages#index'

  get  '/about'       => 'static_pages#about'
  get  '/feedback'    => 'feedbacks#new', :as => 'feedback'
  post '/feedback'    => 'feedbacks#create', :as => 'feedback'

  get  '/words'       => 'entities#index_words'
  get  '/sites'       => 'entities#index_sites'

  post '/words'       => 'entities#create_words', :defaults => { :format => 'json' }
  post '/sites'       => 'entities#create_sites', :defaults => { :format => 'json' }

  get  '/words/:name' => 'entities#show_word', :constraints => { :name => /.*/ }
  get  '/sites/:name' => 'entities#show_site', :constraints => { :name => /.*/ }

  post '/search'      => 'search#index'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Global Trend Finder - #{yield(:title)}
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application', 'highcharts/highcharts'
    = javascript_include_tag 'application', 'fb-sdk'
    = javascript_include_tag 'application', 'twitter'
    = javascript_include_tag 'application', 'ga'
    = csrf_meta_tags
    /[if lt IE 9]
      <script src='http://html5shim.googlecode.com/svn/trunk/html5.js'></script>
  %body
    #fb-root
    %header.navbar.navbar-fixed-top
      .navbar-inner
        .container
          = link_to 'Global Trend Finder', root_path, class: 'brand'
          %nav
            %ul.nav.pull-left
              %li{class: current_page?(root_path) ? 'active' : nil}= link_to 'Home', root_path
              %li{class: current_page?(words_path) ? 'active' : nil}= link_to 'Words', words_path
              %li{class: current_page?(sites_path) ? 'active' : nil}= link_to 'Sites', sites_path
              %li.divider-vertical
              = form_for :search, url: search_path, html: { class: 'navbar-search pull-left' } do |f|
                = f.text_field :query, placeholder: 'Search', class: 'search-query'
            %ul.nav.pull-right
              - if user_signed_in?
                %li{class: current_page?(destroy_user_session_path) ? 'active' : nil}= link_to 'Sign out', destroy_user_session_path, method: :delete
              - else
                %li{class: current_page?(new_user_session_path) ? 'active' : nil}= link_to 'Sign in', new_user_session_path
    .container
      .hero-unit
        - flash.each do |key, value|
          .alert{class: 'alert-' + key.to_s}= value
        = yield
    / TOFIX: center footer alignment
    %footer
      .container
        %ul.nav.nav-pills.pull-left
          %li{class: current_page?(about_path) ? 'active' : nil}= link_to 'About', about_path
          %li{class: current_page?(feedback_path) ? 'active' : nil}= link_to 'Feedback', feedback_path
          %li= link_to 'Blog', 'http://vasil-y.com', target: '_blank'
        %ul.nav.nav-pills.pull-right
          %li.social
            .fb-like{'data-font' => 'arial',
                     'data-href' => 'http://global-trend-finder.com',
                     'data-layout' => 'button_count',
                     'data-send' => 'false',
                     'data-show-faces' => 'true',
                     'data-width' => '150'}
          %li.social
            %a.twitter-share-button{'data-hashtags' => 'globaltf,google',
                                    'data-lang' => 'en',
                                    'data-text' => 'Fun Google Autocomplete Queries',
                                    'data-url' => 'http://global-trend-finder.com',
                                    href: 'https://twitter.com/share'} Tweet